### ISSUE TITLE
New global navigation and board favorites

### ISSUE THREAD

**Issue by jaw-sh** [infinity-next/infinity-next#156]
- [x] Add links for favoriting boards that will be kept in local storage.
- [x] Add "Boards" tab on new navigation.
  - [x] Degrades gracefully without JS, pointing to the Boards Directory.
  - [x] With Javascript, opens a flyout.
  - [x] Show favorited boards, top boards, and most recently active boards.
- [x] Add secondary navigation with favorited boards too, maybe.

**Comment by SEAPUNK** [comment]
One thing I noticed on Chromium is that the board list footer overflows instead of wraps, [making the page wider](http://i.imgur.com/zYqNN9q.png) than it should be -- unless you already have that fixed, I have a small tidbit of CSS to fix that up to [this](http://i.imgur.com/fFT2rGM.png):

```css
.boardlist-items {
    white-space: normal;
}
.boardlist-category,
.boardlist-items {
    display: inline;
    line-height: 1.6em;
}
```

The `line-height` is simply for aesthetic purposes, it gives each row a bit more white space in between each other.
